### ISSUE TITLE
`&mut` bugs

### ISSUE THREAD

**Issue by franziskuskiefer** [hacspec/hax#231]
This issue is collecting bugs in the handling of `&mut`.

The following code is throwing errors.

```rust
let mut bytes = vec![0u8, 1, 2]; // if this is an array, this works
bytes[0] ^= 0xFF; // bytes[0] = bytes[0] ^ 0xFF is accepted
```

```
error[HAX0010]: (RefMut) At this position, Hax was expecting an expression of the shape `&mut _`. Hax forbids `f(x)` (where `f` expects a mutable reference as input) when `x` is not a place expression[1] or when it is a dereference expression.
```

Another instance of this is the following
```
error[HAX0002]: (AndMutDefSite) Fatal error: something we considered as impossible occurred! Please report this by submitting an issue on GitHub!
                Details: Place.of_expr: got `None` for: core::ops::bit::BitAnd::bitand(core::ops::index::Index::index(out, 31), 127)
   --> src/ecdh.rs:243:27
    |
243 |                 out[31] = out[31] & 127u8;
    |                           ^^^^^^^^^^^^^^^
```

**Comment by W95Psp** [comment]
The first snippet of code is failing to extract because the type of `bytes[0]` is an associated type. For now, Hax is not able to look those up. Though, associated types will soon be resolved thanks to the great work of @sonmarcho :smiley:

**Comment by franziskuskiefer** [comment]
> or now, Hax is not able to look those up.

That's a pretty big issue. This is used all over the place.

**Comment by W95Psp** [comment]
Yes, that's the long-standing #20 issue

**Comment by sonmarcho** [comment]
> > or now, Hax is not able to look those up.
> 
> That's a pretty big issue. This is used all over the place. Setting this to P1

Yes, not having support for traits is a big issue, because traits appear everywhere. But I'm almost done with extracting trait information from the Rust compiler, so that should be gone soon. I will keep both of you posted.

**Comment by W95Psp** [comment]
(well, we had support for traits via typeclass resolution in the backends, but we had no pre-resolved instance info :smiley:)

**Comment by W95Psp** [comment]
Update on that:

Now we have associated types correctly resolved, this bug still persist, and is related to to the way `x <OP>= e` is desugared in [import thir](
https://github.com/hacspec/hax/blob/eebfe9b38a621d924794379553a9b263ba7d32bd/engine/lib/import_thir.ml#L499-L501C11).

Basically, when seeing ` lhs <OP>= rhs`, we desugar to `lhs = lhs <OP> rhs`, not touching `lhs` at all.
But `lhs` is sometimes a mutable borrow, and we end up with `&mut something = (&mut something) <OP> rhs`, which is **not** what we want, and which is not even correct with regards to types.

- [ ] stip `&mut`s in import_thir
- [ ] report error when the resulting type after stripping is the expected type (this should be easy to do, AssignOp --aka `... <OP>= ...`-- are only showing up for primitive types, otherwise those are normal calls)

**Comment by W95Psp** [comment]
Let's close in favor of https://github.com/hacspec/hax/issues/491
