### ISSUE TITLE
Static binaries for the engine

### ISSUE THREAD

**Issue by franziskuskiefer** [hacspec/hax#696]
I (@W95Psp) investiguated that:
 - the JS build is quite slow, e.g. on libcrux node overflows, bun doesn't help
 - I tried a few hours to compile the engine statically, with no success
 - we can try is build under alpine with docker, but this will not help for MacOS

Other solutions:
 - arx (with `nix bundle`)
 - docker
 - find wether there is a big bottleneck when extracted in JS  
 - ...

**Comment by W95Psp** [comment]
Here is a small report on trying to produce distributable binaries for the hax-engine.

## OCaml static binaries
After reading https://ocamlpro.com/blog/2021_09_02_generating_static_and_portable_executables_with_ocaml/, I tried this approach but got some issues on linux.
Was not able to try anything on mac.

## Js_of_ocaml
Ended up being either too slow or crashing because of stack overflow. There is no tail call optimization on node, I tried with `bun` wich has some, but got over performance issues.

I also had a issue about caml performances working on strings: parsing JSON was extremely slow, so I had to use JS's own `JSON.parse` and pipe that into the engine.

This solution works for running hax on small crates but performance is really really limiting.

## `nix bundle`
The Nix build of the engine was shipping Rustc and was huge, https://github.com/hacspec/hax/pull/724 solves that.
With that PR, `nix bundle --bundler github:ralismark/nix-appimage ".#hax-engine.bin"` is building a small-ish portable AppImage linux binary. I think that's exactly what we need -- for linux!

## Just ship dynamic binaries
On Mac, the only dynamic library we rely on is `gmp`, we can probably stop relying on zarith and thus get rid of that dependency.

Action items:
 - [ ] use `nix bundle` in the CI to release binaries
 - [ ] try to kill the dependency to `gmp` or copy the dylib over in case of MacOS

**Comment by franziskuskiefer** [comment]
With #734 merged we should be good to go here?

**Comment by W95Psp** [comment]
Yes, indeed! We should make a release and finish the small bit that downloads the engine from GH!

**Comment by W95Psp** [comment]
Shall I just increment the version in `Cargo.toml`, push on crates.io, and push a git ref to the repo?

**Comment by franziskuskiefer** [comment]
Yeah, just make it a `pre.2`.
