### ISSUE TITLE
Support if let guards in pattern matchings

### ISSUE THREAD

**Issue by maximebuyse** [hacspec/hax#814]
[Guards](https://doc.rust-lang.org/rust-by-example/flow_control/match/guard.html) in pattern matchings are supported in Rust but not necessarily in hax backends. We want to support them, and even a generalization with [if-let](https://doc.rust-lang.org/rust-by-example/flow_control/if_let.html) guards (if-lets in guards are a nightly feature in Rust). They should be rewritten by a dedicated phase (see #806).

**Comment by W95Psp** [comment]
@maximebuyse can you add a bit more info here? e.g. link to Rust manual for `if let`, the fact it's nightly, also that we want to support "simple" `if` guards but also `if let` chains in the future (we should btw open new issues for those)

Oh and one important point is that we do `if let`s first because it's helpful for #806
