### ISSUE TITLE
Tuple struct constructors are not always usable

### ISSUE THREAD

**Issue by ROMemories** [hacspec/hax#914]
It seems that tuple struct constructors are not usable in every context.

For instance, the following does not lax check:

```rust
struct Id(u8);

fn main() {
    let ids = [1u8].into_iter().map(Id);
}
```

[view in hax playground](https://hax-playground.cryspen.com/#fstar+tc/dc2725b99a/gist=4b7cb7dead92899c8305a4bdd2004e60)

However, the following does:

```rust
struct Id(u8);

fn main() {
    let id = Id(1u8);
}
```

**Comment by W95Psp** [comment]
Thanks for your bug report!
I need to investigate a bit, but this is definitely `Id` being imported incorrectly by the engine. In `import_thir.ml`, every identity is tagged with a kind, based on the context. Here, I suspect `Id` is seen as a function, whence it gets compiled to `v_Id` instead of `Id`.

It might be that we don't have enough context at THIR import: in this case, we might need to add more information and context in the frontend.
